package com.web.bus.entities;

import javax.persistence.*;

/**

 @author Daksh K
 Description: This class represents an abstract entity that serves as a base for other entities in the application.
 Date: Jan. 2023
 */
@MappedSuperclass // The annotation @MappedSuperclass indicates that this class should be used as a parent class for JPA entities.
public abstract class AbstractEntity {
    /*
    Private Instance Data
    The id field is annotated with the @Id and @GeneratedValue to indicate that it is a primary key
    and should be generated by the database
     */
    /*
    Getter and Setter Methods
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name = "id", nullable = false)
    private Long id;
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        if (id != null) {
            return id.hashCode();
        }
        return super.hashCode();
    }
    /*
    Compare entity object to other entity object
     */
    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof AbstractEntity)) {
            return false; // null or other class
        }
        AbstractEntity other = (AbstractEntity) obj;

        if (id != null) {
            return id.equals(other.id);
        }
        return super.equals(other);
    }
}