spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
  ssl:
    bundle:
      pem:
        kafka:
          truststore:
            certificate: classpath:certs/ca.pem
          keystore:
            certificate: classpath:certs/service.cert
            private-key: classpath:certs/service.key
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-391ed52e-khannad24-1ace.i.aivencloud.com:27441}
    security:
      protocol: SSL
    ssl:
      bundle: kafka
    consumer:
      auto-offset-reset: earliest

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000
  bigquery:
    enabled: false
  seed:
    enabled: true

logging:
  level:
    com.web.bus: INFO
